### ISSUE TITLE
Does this still compile?

### ISSUE THREAD

**Issue by Fran314** [PJayB/jk2src#1]
Has anyone succesfully compiled and ran this project any time recently?
I tried a couple of times, tweak a few things, I had to change one line of code relative to some const char* concatenation. Now it sucesfully builds, but the program won't run... WHAT?

**Comment by PJayB** [comment]
I haven't build this for years. What are you building it with? What errors are you seeing? Is it crashing or what? What do you see in the output window? Also, I encourage you to submit a PR with your code fixes.

**Comment by PJayB** [comment]
I took a look. I fixed the string concatentation issue. Other than that, I can confirm the game launches and is playable. I think you may not have set the Startup Project in VS to "starwars". I updated the README.md with those instructions. Please pull latest master and let me know if it still doesn't work for you.
